### ISSUE TITLE
Extension Failed to Load

### ISSUE THREAD

**Issue by Tanzeel159** [saini-anshul/ulauncher-surfshark#2]
I have downloaded all the necessary requirements and given correct username and password ..as mentioned in the description but still extension fails to load.. am I doing something wrong ?
![Screenshot from 2022-01-05 12-16-45](https://user-images.githubusercontent.com/20295349/148172735-c8d9b096-525d-4687-ad25-0aeee1568b0d.png)

**Comment by saini-anshul** [comment]
Hi @Tanzeel159,

This extension uses **_openvpn_** under the shell to connect to different VPN profiles. Can you check if openvpn is installed on your system? (Check if any of the two commands return a response)

```sh
ls /usr/bin/openvpn
ls /bin/openvpn
```

The extension also uses _**wget**_ and _**unzip**_, so it would be wise to check/install them as well.

If these dependencies are installed and available for use, please provide the logs for uLauncher - it is usually **_~/.local/share/ulauncher/last.log_** file. The log file may provide more details on the error that the extension is running into.

Also, which OS are you using?

**Comment by Tanzeel159** [comment]
https://www.youtube.com/watch?v=VVfnyvUEmYA
I followed this tutorial for openvpn installation 

using the above commands i get no such file or directory 
openvpn is installed in 'etc' folder 
I am using zorin OS
[last.log](https://github.com/saini-anshul/ulauncher-surfshark/files/7819437/last.log)

**Comment by saini-anshul** [comment]
That looks to be the issue. The extension is currently not looking into 'etc' folder for openvpn and thinks that it is not installed.
Thanks for bringing it to my notice. I will update the extension to add 'etc' in paths to look for openvpn.

On the side note, the extension performs the same steps to connect to Surfshark VPN as mentioned in the video.

**Comment by Tanzeel159** [comment]
Oh cool looking forward to it
That's awesome . this extension will make it easier to connect to different servers quickly .

**Comment by saini-anshul** [comment]
The issue has been fixed and tested on Zorin OS (should work on all Ubuntu based destros).
Please update the extension on uLauncher to get the changes. Let me know if you still face the issue.

**Comment by Tanzeel159** [comment]
Yes I just updated the extension. It works flawlessly . Thank you for your work !!!
